spring:
  profiles:
    active: 
    -  dev
---

server:
  port: 8001
  
  
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: sailing
    url: jdbc:mysql://localhost:3306/cloudDB01?characterEncoding=utf-8&useSSL=false
    
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.atguigu.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml

    
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http:localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka
    instance-id: dept-8001 #修改本工程在eureka服务中的名字
    prefer-ip-address: true  #访问路径可以显示IP地址
info: #eureka服务中超链接配置
  app.name: atguigu-microservicecloud-springcloudconfig01
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
    
---
server:
  port: 8001
  
  
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: sailing
    url: jdbc:mysql://localhost:3306/cloudDB01?characterEncoding=utf-8&useSSL=false
    
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.atguigu.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml

    
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http:localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001 #修改本工程在eureka服务中的名字
    prefer-ip-address: true  #访问路径可以显示IP地址
info: #eureka服务中超链接配置
  app.name: atguigu-microservicecloud-springcloudconfig02
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$